INSERT INTO Trainee (Traineeid, name) VALUES (1, 'Daryl Conway')
INSERT INTO Trainee (Traineeid, name) VALUES (2, 'Michael Massey')
INSERT INTO Trainee (Traineeid, name) VALUES (3, 'George Timbrell')
INSERT INTO Subjects (id, subjectName, subjectRating, TraineeId) VALUES (1, 'Java', 5, 1)
INSERT INTO Subjects (id, subjectName, subjectRating, TraineeId) VALUES (2, 'JavaScript', 5, 1)
INSERT INTO Subjects (id, subjectName, subjectRating, TraineeId) VALUES (3, 'Databases', 5, 1)
INSERT INTO Subjects (id, subjectName, subjectRating, TraineeId) VALUES (4, 'CI', 5, 1)
INSERT INTO Subjects (id, subjectName, subjectRating, TraineeId) VALUES (5, 'Java', 5, 2)
INSERT INTO Subjects (id, subjectName, subjectRating, TraineeId) VALUES (6, 'JavaScript', 5, 2)
INSERT INTO Subjects (id, subjectName, subjectRating, TraineeId) VALUES (7, 'Databases', 5, 2)
INSERT INTO Subjects (id, subjectName, subjectRating, TraineeId) VALUES (8, 'CI', 5, 2)
INSERT INTO Subjects (id, subjectName, subjectRating, TraineeId) VALUES (9, 'Java', 5, 3)
INSERT INTO Subjects (id, subjectName, subjectRating, TraineeId) VALUES (10, 'JavaScript', 5, 3)
INSERT INTO Subjects (id, subjectName, subjectRating, TraineeId) VALUES (11, 'Databases', 5, 3)
INSERT INTO Subjects (id, subjectName, subjectRating, TraineeId) VALUES (12, 'CI', 5, 3)